spring:
  jpa.hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/reaktor_schoolManagerServer?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
server:
  port: 8087
logging:
    level:
        root: INFO
    file:
        name: /tmp/reaktor_schoolManagerServer.log
        max-size: 1MB
        max-history: 10
        total-size-cap: 10MB

reaktor:
  publicKeyFile: ${PUBLIC_KEY_FILE}
  urlCors: https://somos.iesjandula.es
  reiniciarConstantes: true
  constantes:
    seleccionHorariosPorClaustro: ""